#!/bin/sh

export EDITOR=vim
export VERSION_CONTROL=numbered
export SVN_EDITOR=$EDITOR
export LANG="ru_RU.UTF-8"
export OOO_FORCE_DESKTOP=gnome
export LC_COLLATE=C
export HISTCONTROL=ignorespace:erasedups

export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$HOME/local/bin:$PATH"

FREETYPE=$(dirname $(readlink /run/current-system/sw/lib/libfreetype.so))
export LD_LIBRARY_PATH="$FREETYPE:$LD_LIBRARY_PATH"

XFT=$(dirname $(readlink /run/current-system/sw/lib/libXft.so))
export LD_LIBRARY_PATH="$XFT:$LD_LIBRARY_PATH"

if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi
